// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Domain.DbContexts;

#nullable disable

namespace UrlShortener.Domain.Migrations
{
    [DbContext(typeof(UrlShortenerDbContext))]
    [Migration("20240126165633_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Contracts.Models.UrlShortenerModel", b =>
                {
                    b.Property<string>("ModifiedUrl")
                        .HasColumnType("text")
                        .HasColumnName("modified_url");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("OriginUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin_url");

                    b.HasKey("ModifiedUrl");

                    b.ToTable("url_shortener");
                });
#pragma warning restore 612, 618
        }
    }
}
